#!/bin/bash -i

checkInstalled(){
  REQUIRED_PKG=$1;
  PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
  echo Checking for $REQUIRED_PKG: $PKG_OK
  if [ "" = "$PKG_OK" ]; then
    echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
    sudo sudo apt-get --yes install $REQUIRED_PKG
  fi
}

#sudo apt-get update
checkInstalled "python3-pip"
#pip install -r requirements.txt
checkInstalled "cython"
checkInstalled "libzmq3-dev"
checkInstalled "libelf-dev"
checkInstalled "python3-tk"
#echo 'export ZCM_DEFAULT_URL=ipc' >> ~/.bashrc
#(cd ../ZeroCM* && python3 waf configure --use-python --use-ipc --use-zmq --use-elf)
mv ../CoppeliaSim* ../CoppeliaSim
mkdir ../CoppeliaSim/jaco_data
#(cd ../CoppeliaSim* && cd programming/zmqRemoteApi/clients/python && curDir=$(pwd) && echo "export PYTHONPATH=$curDir:\$PYTHONPATH" >> ~/.bashrc)
source ~/.bashrc
echo "Project Jaco installed successfully!"
