/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class euler_t implements lcm.lcm.LCMEncodable
{
    public boolean available;
    public float pitch;
    public float roll;
 
    public euler_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdd4e324c3878914eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.euler_t.class))
            return 0L;
 
        classes.add(lcmtypes.euler_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.available ? 1 : 0); 
 
        outs.writeFloat(this.pitch); 
 
        outs.writeFloat(this.roll); 
 
    }
 
    public euler_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public euler_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.euler_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.euler_t o = new lcmtypes.euler_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.available = ins.readByte()!=0;
 
        this.pitch = ins.readFloat();
 
        this.roll = ins.readFloat();
 
    }
 
    public lcmtypes.euler_t copy()
    {
        lcmtypes.euler_t outobj = new lcmtypes.euler_t();
        outobj.available = this.available;
 
        outobj.pitch = this.pitch;
 
        outobj.roll = this.roll;
 
        return outobj;
    }
 
}

