/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class imus_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public lcmtypes.euler_t imu_values[];
 
    public imus_t()
    {
        imu_values = new lcmtypes.euler_t[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc2d9e23567dc1d94L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.imus_t.class))
            return 0L;
 
        classes.add(lcmtypes.imus_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + lcmtypes.euler_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 4; a++) {
            this.imu_values[a]._encodeRecursive(outs); 
        }
 
    }
 
    public imus_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public imus_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.imus_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.imus_t o = new lcmtypes.imus_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.imu_values = new lcmtypes.euler_t[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.imu_values[a] = lcmtypes.euler_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public lcmtypes.imus_t copy()
    {
        lcmtypes.imus_t outobj = new lcmtypes.imus_t();
        outobj.utime = this.utime;
 
        outobj.imu_values = new lcmtypes.euler_t[(int) 4];
        for (int a = 0; a < 4; a++) {
            outobj.imu_values[a] = this.imu_values[a].copy();
        }
 
        return outobj;
    }
 
}

